import { DepartmentKeys } from '../model';

const subDepartments: Record<DepartmentKeys, Array<string>> = {
  apparel: [
    'Tops',
    'Bottoms',
    'Dresses',
    'Suits',
    'Activewear',
    'Sleepwear',
    'Formal Wear',
    'Casual Wear',
    'Apparel',
    'Petite Apparel',
    'Maternity Apparel',
    'Workwear',
    'Uniforms',
    'Costumes',
  ],
  shoes: [
    'Athletic Shoes',
    'Boots',
    'Sneakers',
    'Sandals',
    'Flats',
    'Heels',
    'Slippers',
    'Shoes',
    'Casual Shoes',
    'Dress Shoes',
    'Outdoor Shoes',
    'Specialty Shoes',
  ],
  accessories: [
    'Bags',
    'Belts',
    'Hats',
    'Scarves',
    'Gloves',
    'Ties',
    'Socks',
    'Wallets',
    'Jewelry',
    'Watches',
    'Eyewear',
    'Hair Accessories',
    'Umbrellas',
    'Tech Accessories',
    'Travel Accessories',
  ],
  jewelry: [
    'Rings',
    'Necklaces',
    'Earrings',
    'Bracelets',
    'Anklets',
    'Brooches',
    'Pendants',
    'Chains',
    'Charms',
    'Watches',
  ],
  handbags: [
    'Totes',
    'Shoulder Bags',
    'Clutches',
    'Crossbody Bags',
    'Backpacks',
    'Satchels',
    'Hobo Bags',
    'Wallets',
    'Wristlets',
    'Messenger Bags',
    'Briefcases',
  ],
  eyewear: [
    'Sunglasses',
    'Prescription Glasses',
    'Reading Glasses',
    'Contact Lenses',
    'Eyeglass Frames',
    'Eyeglass Cases',
    'Eyeglass Chains',
    'Eyeglass Accessories',
  ],
  watches: [
    'Analog',
    'Digital',
    'Smart',
    'Luxury',
    'Sport',
    'Fashion',
    'Casual',
    'Dress',
    'Childrens',
    'Pocket Watches',
  ],
  beauty: [
    'Skincare',
    'Makeup',
    'Fragrances',
    'Hair Care',
    'Nail Care',
    'Bath & Body',
    'Personal Care',
    "Men's Grooming",
    'Beauty Tools',
    'Wellness Products',
    'Cosmetics Accessories',
  ],
  lingerie: [
    'Bras',
    'Panties',
    'Lingerie Sets',
    'Shapewear',
    'Sleepwear',
    'Robes',
    'Camisoles',
    'Slips',
    'Bodysuits',
    'Hosiery',
    'Lingerie Accessories',
  ],
  swimwear: [
    'Bikinis',
    'One-Piece Swimsuits',
    'Tankinis',
    'Cover-Ups',
    'Rash Guards',
    'Dresses',
    'Shorts',
    'Swim Accessories',
  ],
  'athletic-wear': [
    'Sports Bras',
    'Tops',
    'Bottoms',
    'Jackets',
    'Shorts',
    'Pants',
    'Performance Shoes',
    'Accessories',
    'Gym Bags',
    'Workout Gear',
  ],
  'formal-wear': [
    'Tuxedos',
    'Evening Gowns',
    'Cocktail Dresses',
    'Suits',
    'Shirts',
    'Pants',
    'Skirts',
    'Accessories',
  ],
  'casual-wear': [
    'Jeans',
    'T-Shirts',
    'Polos',
    'Sweaters',
    'Hoodies',
    'Shorts',
    'Dresses',
    'Pants',
    'Skirts',
    'Jackets',
    'Tops',
  ],
  outerwear: [
    'Coats',
    'Jackets',
    'Vests',
    'Parkas',
    'Raincoats',
    'Windbreakers',
    'Winter Jackets',
    'Blazers',
    'Ponchos',
    'Capes',
  ],
  'childrens-clothing': [
    "Boys' Clothing",
    "Girls' Clothing",
    'Infant Clothing',
    'Toddler Clothing',
    "Kids' Shoes",
    "Kids' Accessories",
    'School Uniforms',
    'Costumes',
  ],
  'maternity-wear': [
    'Tops',
    'Bottoms',
    'Dresses',
    'Lingerie',
    'Swimwear',
    'Activewear',
    'Outerwear',
    'Nursing Bras',
    'Nursing Tops',
    'Nursing Dresses',
    'Maternity Accessories',
  ],
  'plus-size-clothing': [
    'Tops',
    'Bottoms',
    'Dresses',
    'Activewear',
    'Lingerie',
    'Outerwear',
    'Swimwear',
    'Formal Wear',
    'Casual Wear',
    'Workwear',
  ],
  'vintage-clothing': [
    'Tops',
    'Bottoms',
    'Dresses',
    'Suits',
    'Outerwear',
    'Accessories',
    'Shoes',
    'Handbags',
    'Jewelry',
    'Lingerie',
  ],
  streetwear: [
    'Tops',
    'Bottoms',
    'Dresses',
    'Jackets',
    'Hoodies',
    'Accessories',
    'Sneakers',
    'Caps',
    'Beanies',
    'Backpacks',
    'Fanny Packs',
  ],
  'ethnic-wear': [
    'Jewelry',
    'Accessories',
    'Footwear',
    'Outerwear',
    'Dresses',
    'Suits',
    'Tops',
    'Bottoms',
  ],
  workwear: [
    'Office Attire',
    'Business Casual',
    'Professional Clothing',
    'Uniforms',
    'Corporate Wear',
    'Shoes',
    'Accessories',
    'Bags',
    'Tools',
    'Safety Gear',
  ],
  uniforms: [
    'Medical Scrubs',
    'Military Uniforms',
    'School Uniforms',
    'Sports Uniforms',
    'Service Industry Uniforms',
    'Security Uniforms',
    'Hospitality Uniforms',
    'Corporate Uniforms',
  ],
  costumes: [
    'Halloween',
    'Theatrical',
    'Cosplay',
    'Fantasy',
    'Historical',
    'Superhero',
    'Character',
    'Animal',
    'Fairy Tale',
    'Funny',
  ],
};

export const getSubDepartments = (departmentName: DepartmentKeys) => {
  return subDepartments[departmentName];
};
